name:           roopc.net

url:            http://roopc.net
domain:         roopc.net

# Comment out when deploying
# url:              http://localhost:8082
# domain:           localhost:8082

permalink:   /:categories/:year/:title

markdown:    'kramdown'
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge

# markdown:    'redcarpet'
# redcarpet:
#     extensions: [ 'smart', 'no_intra_emphasis', 'autolink' ]

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

timezone: 'Asia/Kolkata'

popular-posts:
  - /posts/2014/imagining-split-screen-ipad
